### ISSUE TITLE
I wonder if you have a plan to support RG280M.

### ISSUE THREAD

**Issue by maidhunter1** [Ninoh-FOX/RG280V_ROGUE#1]
Hello
rogue is a nice firmware. It works perfectly on my rg280v.
However, the analog stick does not work in rg280m. 
Is there any way to use this nice firmware on rg280m too? 
I would be really happy if possible.
Thank you again for making the wonderful firmware.

**Comment by Ninoh-FOX** [comment]
I don't have the rg280m model, is for this that not has ROGUE, because I can't test the firmware previous to release.

**Comment by maidhunter1** [comment]
Thank you for your reply.

**Comment by Ninoh-FOX** [comment]
this weekend I go to release the version for RG280M, I will get a console this week

**Comment by maidhunter1** [comment]
I don't have a device right now, but I will get it again. Thank you for your consideration.

**Comment by Ninoh-FOX** [comment]
Done!!
