### ISSUE TITLE
Boot Issues, Battery Drain, Emulation/Sound Stutter

### ISSUE THREAD

**Issue by rtnario** [Ninoh-FOX/RG280V_ROGUE#2]
I chose to install RG280V ROGUE for my unit (v1.7.10u17) because it has better performance than stock. However I noticed a couple of issues since I installed ROGUE:

- difficulty booting the device, when I hold the power button the LED indicator stays dimly lit, I have to mash on power and reset a number of times just to get it to boot
- battery indicator jumps percentages
- taking many hours to charge, was not this way before. left overnight and LED indicator was still charging, but charger works normally with other devices
- strange emulation/sound stuttering at times where frames will be skipped, sound stuttering especially noticeable with GBA and SNES emulation

I also have ROGUE installed on my RG350 but I've never encountered a single one of these issues on there, so this is strange to me. I'm not sure how or where to point out these issues, so I'm raising them here for you to see.

**Comment by Ninoh-FOX** [comment]
Let's see, everything seems to indicate an bad update. 
Have you followed the steps?
Have you burned sd_image.bin into a new, quality microsd?
Upgrading from stock nl is good as it gives problems, that's why I always insist on a clean install.

**Comment by rtnario** [comment]
Thanks for the response! Thing is this was already from a clean installation using sd_image.bin. However I'll experiment on microSD cards with the latest ROGUE to see if I'll still observe these issues.

**Comment by rtnario** [comment]
I've updated to v1.7.10u19, used a freshly formatted 16GB microSD. No more stuttering in emulation, close to 0 stuttering when it comes to sound. Battery is feeling more accurate so I'm now confident that it really was just a microSD issue in the end. Also, I'm consistently powering on and off the device without problems.

Thanks for the help! Hope this helps anyone else experiencing similar issues.
