### ISSUE TITLE
Cyclic reboot

### ISSUE THREAD

**Issue by bigfatbrowncat** [Ninoh-FOX/RG280V_ROGUE#3]
Hi! I've managed to build the sd_image from your repo and flashed it into my RG280V SD-card.

The console starts to boot, shows the graphical logo, reports that it is creating a swap (but I don't see any progress bar change there), shows that it "wipes the old config" and reboots. Then the same repeats over and over.

How to debug this? What could be the problem?

I was building in Ubuntu 18.04, had to make some small patches in the build scripts, but I haven't changed any C/C++ code and haven't changed anything major.

**Comment by Ninoh-FOX** [comment]
It seems that it does not create the files in the data partition, that is why it is looping.

**Comment by Ninoh-FOX** [comment]
can you report this in the git of the toolchain?  this is for release only.

**Comment by bigfatbrowncat** [comment]
Thank you!
I've created: https://github.com/Ninoh-FOX/toolchain/issues/5
