### ISSUE TITLE
Screen Brightness

### ISSUE THREAD

**Issue by falkenhawk** [Ninoh-FOX/RG280V_ROGUE#4]
Hi, thanks for your hard work on this alternative firmware.
I installed the latest build v1.7.12 and noticed that brightness level 1 is barely visible even in a completely dark room, but brightness level 2 is already quite bright in a completely dark room.
Would it be possible to distribute the brightness control more evenly, so that there are 1-2 levels in between the darkest, almost invisible and the current level 2 of brightness? 🙏

**Comment by Ninoh-FOX** [comment]
right now i was looking at that, Anyway, download the update again, I re-uploaded it last night.

**Comment by falkenhawk** [comment]
@Ninoh-FOX thank you, the lowest brightness is now imo good for night gaming.
However the distribution for other levels is uneven.
I will refer to the brightness values which I can see GMenu2X settings. I can see the differences on 5-50 range, but any value above that (55-150) looks the same to my eye. Perhaps it's intentional to allow changing the brightness faster with fewer button clicks? (as we probably don't need that many levels anyway)

**Comment by Ninoh-FOX** [comment]
For some reason, the RG280V's screen only changes brightness below 30% of the total value, and I don't know why, the RG280M doesn't have this problem.
