### ISSUE TITLE
pcsx4all and fceux emulators not starting

### ISSUE THREAD

**Issue by falkenhawk** [Ninoh-FOX/RG280V_ROGUE#5]
Hello,
I have troubles emulating psx & nes.
The bundled pcsx4all emulator returns back to gmenu2x immediately after selecting any game. I also tried two other versions I found on the Internet with same result.

NES/Famicom emulator was not included in Rogue, so I tried https://gitlab.com/gameblabla/gameblabla-releases/-/blob/master/opk/gcw0/fceux_gcw0.opk but it also behaves the same - it does not start any game and returns back to gmenu2x.

I tried copying bios files to appropriate folders `/usr/local/home/.pcsx4all` and `/user/local/home/.fceux` respectively, but it didn't help.

**Comment by Ninoh-FOX** [comment]
This is because that version is for OD beta

**Comment by falkenhawk** [comment]
FWIW, I've just copied fceux out of the stock fw, and it still does not work - returns back to gmenu2x.

**Comment by falkenhawk** [comment]
sorry, I wrote too soon. Stock Fceux was not starting because I had the bios file in `/user/local/home/.fceux` named `DISKSYS.ROM`. (all caps) I renamed it to `disksys.rom` and it works now 🙈

Perhaps you could add it to your build to avoid confusion 🙏

**Comment by Ninoh-FOX** [comment]
Well, is all work fine close please

**Comment by falkenhawk** [comment]
The issue is that fceux is not included in rogue cfw. Could you perhaps add it please? 🙏 Bios files are also probably needed for fceux and maybe also for pcsx4all emulator too.
EDIT: but I am still a noob so I might be wrong about bios files.

**Comment by Ninoh-FOX** [comment]
I can't include bios for legal problems.

But I can put the nes emulator version that I use. Anyway, you only need find the more recent version for stock firmware.
https://github.com/SeongGino/RetroGame350-AppRepo/blob/master/Emulators/FCEUX_2019-11-15.opk
